export const TIPOLOGIAS = [
  { value: 'quirurgicos', label: 'Quirúrgicos' },
  { value: 'hemodialisis', label: 'Hemodiálisis' },
  { value: 'estetica', label: 'Estética' },
  { value: 'oncologico', label: 'Oncológico' },
  { value: 'opticas', label: 'Ópticas' },
  { value: 'centambulatorios', label: 'Centros Ambulatorios' },
  { value: 'clinica', label: 'Clínica / Internación' },
  { value: 'consultorios', label: 'Consultorios' },
  { value: 'laboratorio', label: 'Laboratorio' },
  { value: 'hemoterapia', label: 'Hemoterapia' },
  { value: 'radiodiagnostico', label: 'Radiodiagnóstico' },
  { value: 'obra', label: 'Obra' },
];

export const SECCIONES_POR_TIPOLOGIA = {
  quirurgicos: [
    'conclusion',
    'registros',
    'datos_generales',
    'consultorios_externos',
    'consultorios_salud_mental',
    'la_institucion_posee',
    'sector_internacion',
    'enfermeria',
    'area_quirurgica',
    'obstetricia',
    'laboratorio',
    'guardia',
    'uco',
    'uti',
    'utin',
    'hemodinamia',
    'hospital_dia',
    'quirurgicos_inscripcion',
    'quirurgicos_direccion_funcionamiento',
    'quirurgicos_enfermeria',
    'quirurgicos_area_internacion',
    'quirurgicos_equipamiento',
    'quirurgicos_esterilizacion',
  ],
  hemodialisis: [
    'conclusion',
    'registros',
    'datos_generales',
    'sector_internacion',
    'enfermeria',
    'hemodialisis_direccion_funcionamiento',
    'hemodialisis_analisis_agua',
    'hemodialisis_serologia',
  ],
  estetica: [
    'conclusion',
    'registros',
    'datos_generales',
    'estetica_inscripcion',
    'estetica_direccion_funcionamiento',
    'estetica_consultorios',
  ],
  oncologico: [
    'conclusion',
    'registros',
    'datos_generales',
    'estetica_inscripcion',
    'estetica_direccion_funcionamiento',
    'estetica_consultorios',
  ],
  opticas: [
    'conclusion',
    'registros',
    'opticas_local',
    'opticas_taller',
    'opticas_gabinete_contactologia',
  ],
  centambulatorios: [
    'conclusion',
    'registros',
    'datos_generales',
    'consultorios_externos',
    'sector_internacion',
    'enfermeria',
    'centamb_inscripcion',
    'centamb_direccion_funcionamiento',
    'centamb_esterilizacion',
  ],
  clinica: [
    'conclusion',
    'registros',
    'datos_generales',
    'consultorios_externos',
    'consultorios_salud_mental',
    'la_institucion_posee',
    'radiofisica',
    'sector_internacion',
    'enfermeria',
    'area_quirurgica',
    'obstetricia',
    'laboratorio',
    'guardia',
    'uco',
    'uti',
    'utin',
    'hemodinamia',
    'hospital_dia',
  ],
  consultorios: ['conclusion', 'consultorios_general', 'direccion_funcionamiento'],
  laboratorio: ['conclusion', 'laboratorio_general', 'direccion_funcionamiento'],
  hemoterapia: ['conclusion', 'hemoterapia_general', 'direccion_funcionamiento'],
  radiodiagnostico: ['conclusion', 'radiodiagnostico_general', 'direccion_funcionamiento'],
  obra: ['conclusion'],
};

export const SECCION_LABELS = {
  conclusion: 'Conclusión de la Inspección',
  registros: 'Registros',
  datos_generales: 'Datos Generales',
  consultorios_externos: 'Consultorios Externos',
  consultorios_salud_mental: 'Consultorios Salud Mental',
  la_institucion_posee: 'La Institución Posee',
  radiofisica: 'Radiofísica',
  sector_internacion: 'Sector de Internación',
  enfermeria: 'Enfermería',
  area_quirurgica: 'Área Quirúrgica',
  obstetricia: 'Obstetricia',
  laboratorio: 'Laboratorio',
  guardia: 'Guardia',
  uco: 'Unidad Coronaria de Cuidados Intensivos (UCO)',
  uti: 'Unidad de Terapia Intensiva (UTI)',
  utin: 'Unidad de Terapia Intensiva Neonatal (UTIN)',
  hemodinamia: 'Hemodinamia',
  hospital_dia: 'Hospital de Día',
  quirurgicos_inscripcion: 'De la Inscripción y Habilitación',
  quirurgicos_direccion_funcionamiento: 'De la Dirección y Funcionamiento',
  quirurgicos_enfermeria: 'Enfermería',
  quirurgicos_area_internacion: 'Área Internación',
  quirurgicos_equipamiento: 'Del Equipamiento',
  quirurgicos_esterilizacion: 'Esterilización',
  quirurgicos_general: 'Quirúrgicos - General',
  hemodialisis_direccion_funcionamiento: 'Dirección y Funcionamiento - Hemodiálisis',
  hemodialisis_analisis_agua: 'Análisis de Agua',
  hemodialisis_serologia: 'Serología',
  hemodialisis_serologia_personal: 'Serología del Personal',
  hemodialisis_serologia_pacientes: 'Serología de Pacientes',
  estetica_inscripcion: 'De la Inscripción y Habilitación',
  estetica_direccion_funcionamiento: 'Dirección y Funcionamiento',
  estetica_consultorios: 'Consultorios',
  opticas_local: 'Local',
  opticas_taller: 'Taller',
  opticas_gabinete_contactologia: 'Gabinete de Contactología',
  optica_general: 'Óptica - General',
  centamb_inscripcion: 'De la Inscripción y Habilitación',
  centamb_direccion_funcionamiento: 'Dirección y Funcionamiento',
  centamb_esterilizacion: 'Esterilización',
  consultorios_general: 'Consultorios - General',
  laboratorio_general: 'Laboratorio - General',
  hemoterapia_general: 'Hemoterapia - General',
  radiodiagnostico_general: 'Radiodiagnóstico - General',
  internacion_general: 'Internación - General',
  emergencias_general: 'Emergencias - General',
  salud_mental_general: 'Salud Mental - General',
  odontologia_general: 'Odontología - General',
  farmacia_general: 'Farmacia - General',
  direccion_funcionamiento: 'Dirección y Funcionamiento',
};

export const INSPECTORES = [
  { nombre: "FABIAN AVILA", dni: "92854906" },
  { nombre: "CRISTIAN RECALDE", dni: "25202207" },
  { nombre: "DIEGO CLAVERO", dni: "18302479" },
  { nombre: "ESTEBAN ANDRES GARATE", dni: "26179040" },
  { nombre: "FABIAN EDUARDO RINALDI", dni: "17597097" },
  { nombre: "PAULA ANDREA RUIZ", dni: "20307675" },
  { nombre: "SERGIO GERMAN ARROYO", dni: "20363941" },
  { nombre: "JOSE LUIS PATRIGNANI", dni: "24188491" },
  { nombre: "PABLO VALLE", dni: "22078426" },
  { nombre: "MOIRA MAZA", dni: "25608474" },
  { nombre: "FLORENCIA MEJIASE", dni: "39822099" },
  { nombre: "CAMILA PUCA", dni: "41530952" },
];
